# Generated by Django 5.2.9 on 2026-06-19 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_add_review_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='name',
            field=models.CharField(choices=[('Базовый', 'Базовый — 2 часа'), ('Стандарт', 'Стандарт — 3 часа'), ('Премиум', 'Премиум — 4 часа')], max_length=10, unique=True, verbose_name='Название'),
        ),
    ]
