# Generated by Django 5.2.9 on 2026-06-19 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_package_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='name',
            field=models.CharField(choices=[('light', 'Light — 2 часа'), ('standard', 'Standard — 3 часа'), ('premium', 'Premium — 4 часа')], max_length=10, unique=True, verbose_name='Название'),
        ),
    ]
