# Generated by Django 5.2.9 on 2026-06-19 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_package_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='name',
            field=models.CharField(choices=[('light', 'Базовый — 2 часа'), ('standard', 'Стандарт — 3 часа'), ('premium', 'Премиум — 4 часа')], max_length=10, unique=True, verbose_name='Название'),
        ),
    ]
